# Intro to Sckit-Learning Models

What we are going to learn

0. An end to end Scikit Learn Workflow.
1. Getting Data Ready
2. Choose the estimator/algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data.
4. Evaluating a model.
5. Improve the model.
6. Save and Load a Trained Model.
7. Putting it all Together!

## An end-to-end Scikit Learn Workflow.

In [20]:
# 1. Get the Data Ready
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [21]:
# Create X (Features Matrix) 

# NOTE : Dont Forget to mention Axis When Dropping
X = heart_disease.drop("target",axis=1)

# Create Labels
y = heart_disease["target"]

In [22]:
# Choose the estimator/algorithm for our problems 
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [23]:
# Fit the model to the Training Data.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [24]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [28]:
# make a prediction
y_label = clf.predict(np.array([0,1,2,3,4]))

ValueError: Expected 2D array, got 1D array instead:
array=[0. 1. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [29]:
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0], dtype=int64)

In [31]:
clf.score(X_train,y_train)

1.0

In [34]:
clf.score(X_test,y_test)

0.8524590163934426

In [36]:
from sklearn.metrics import classification_report , confusion_matrix, accuracy_score

print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.92      0.76      0.83        29
           1       0.81      0.94      0.87        32

    accuracy                           0.85        61
   macro avg       0.86      0.85      0.85        61
weighted avg       0.86      0.85      0.85        61



In [37]:
print(confusion_matrix(y_test,y_preds))

[[22  7]
 [ 2 30]]


In [38]:
print(accuracy_score(y_test,y_preds))

0.8524590163934426


In [42]:
y_test

207    0
121    1
94     1
87     1
85     1
      ..
189    0
122    1
164    1
220    0
251    0
Name: target, Length: 61, dtype: int64

In [43]:
y_preds

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0], dtype=int64)

In [54]:
# Improve a Model 
np.random.seed(42)
for i in range(10,100,10):
    print(F"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(F"Model accuracy on test set:{clf.score(X_test,y_test)*100:2f}%")
    print("")

Trying model with 10 estimators...
Model accuracy on test set:81.967213%

Trying model with 20 estimators...
Model accuracy on test set:86.885246%

Trying model with 30 estimators...
Model accuracy on test set:85.245902%

Trying model with 40 estimators...
Model accuracy on test set:81.967213%

Trying model with 50 estimators...
Model accuracy on test set:85.245902%

Trying model with 60 estimators...
Model accuracy on test set:86.885246%

Trying model with 70 estimators...
Model accuracy on test set:90.163934%

Trying model with 80 estimators...
Model accuracy on test set:90.163934%

Trying model with 90 estimators...
Model accuracy on test set:86.885246%



In [55]:
import pickle
pickle.dump(clf,open("random_forest_model_1.pkl","wb"))

In [56]:
loaded_model = pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.score(X_test,y_test)

0.8688524590163934