In [1]:
import numpy as np

In [40]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
              [4,6,7],
              [5,8,9]])
a2

array([[1, 2, 3],
       [4, 6, 7],
       [5, 8, 9]])

In [5]:
a3 = np.array([[[1,2,3],
                [2,8,5],
               [5,6,7,]],
               [[11,23,65],
               [56,76,22],
               [23,41,52]]])
a3

array([[[ 1,  2,  3],
        [ 2,  8,  5],
        [ 5,  6,  7]],

       [[11, 23, 65],
        [56, 76, 22],
        [23, 41, 52]]])

In [6]:
a1.shape

NameError: name 'a1' is not defined

In [7]:
a1.shape

NameError: name 'a1' is not defined

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim, a3.ndim

NameError: name 'a1' is not defined

In [10]:
a3.size

18

# Create DataFrame with Numpy Array

In [95]:
import pandas as pd

In [12]:
df = pd.DataFrame(a2)

In [13]:
df

0  1  2
0  1  2  3
1  4  6  7
2  5  8  9

## 4. Manipulating Array

### Arithmetic 

In [14]:
a1

NameError: name 'a1' is not defined

In [ ]:
ones = np.ones(3)
ones

In [ ]:
twos = np.full(3,5)
twos

In [15]:
a1 + twos

NameError: name 'a1' is not defined

In [16]:
massive_array = np.random.random(10000)

In [17]:
massive_array[:10]

array([0.68855073, 0.16861245, 0.67742411, 0.75571519, 0.64687397,
       0.7599597 , 0.72213066, 0.3776631 , 0.78034167, 0.86838876])

In [18]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

985 µs ± 57.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
7.5 µs ± 605 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
np.var(a2)

6.666666666666667

In [22]:
a2

array([[1, 2, 3],
       [4, 6, 7],
       [5, 8, 9]])

In [23]:
np.std(a2)

2.581988897471611

In [24]:
np.sqrt(np.var(a2))

2.581988897471611

## Reshape

In [26]:
a2.shape

(3, 3)

In [60]:
a1_reshape = a1.reshape(1,3)
a2_reshape = a2.reshape(3,3,1)

In [63]:
a2_reshape * a1_reshape

array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9]],

       [[ 4,  8, 12],
        [ 6, 12, 18],
        [ 7, 14, 21]],

       [[ 5, 10, 15],
        [ 8, 16, 24],
        [ 9, 18, 27]]])

## Read BroadCasting Rules Before Performing these Above Action

## Transpose switches the axis's of the array

In [64]:
a2.T

array([[1, 4, 5],
       [2, 6, 8],
       [3, 7, 9]])

In [65]:
a1.T

array([1, 2, 3])

In [66]:
a1

array([1, 2, 3])

In [67]:
a1_reshape.T

array([[1],
       [2],
       [3]])

In [68]:
a1_reshape

array([[1, 2, 3]])

In [69]:
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [6],
        [7]],

       [[5],
        [8],
        [9]]])

In [70]:
a1_reshape.T

array([[1],
       [2],
       [3]])

In [71]:
a2_reshape.T

array([[[1, 4, 5],
        [2, 6, 8],
        [3, 7, 9]]])

In [72]:
a3.shape

(2, 3, 3)

In [73]:
a3.T.shape

(3, 3, 2)

In [74]:
a3.T

array([[[ 1, 11],
        [ 2, 56],
        [ 5, 23]],

       [[ 2, 23],
        [ 8, 76],
        [ 6, 41]],

       [[ 3, 65],
        [ 5, 22],
        [ 7, 52]]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 2,  8,  5],
        [ 5,  6,  7]],

       [[11, 23, 65],
        [56, 76, 22],
        [23, 41, 52]]])

## Dot Product 

In [76]:
np.random.seed(0)

In [77]:
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [78]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [79]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

## Elementwise-Multiplication (Hadamard Product)

In [80]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

## Dot Product

In [81]:
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [82]:
mat_2_t = mat2.T

In [83]:
np.dot(mat1, mat_2_t)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot Product Nut Butter Sale

In [89]:
np.random.seed(0)
## Number of Jars Sold
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

### Create Weekly Sales 

In [144]:
weekly_sales = pd.DataFrame(sales_amount,index = ["Mon", "Tue","Wed", "Thur","Fri"],columns=["Almond","Peanut","Cashew"])
weekly_sales

Almond  Peanut  Cashew
Mon       12      15       0
Tue        3       3       7
Wed        9      19      18
Thur       4       6      12
Fri        1       6       7

#### Create Prices

In [145]:
prices = np.array([10,12,8])
prices = prices.reshape(1,3)
prices
weekly_sales.shape

(5, 3)

In [146]:
# Check Shape of array if only one array is passed 
prices_data = pd.DataFrame(prices,index=["Prices"], columns=["Almond","Peanut","Cashew"])
prices_data

Almond  Peanut  Cashew
Prices      10      12       8

## Change Alignment if Shape aren't aligned using Transpose

In [147]:
daily_sales = prices_data.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thur  Fri
Prices  300  122  462   208  138

In [149]:
## Doesn't Work not the right Shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Wrong number of items passed 5, placement implies 1

In [150]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond  Peanut  Cashew  Total ($)
Mon       12      15       0        300
Tue        3       3       7        122
Wed        9      19      18        462
Thur       4       6      12        208
Fri        1       6       7        138

## Comparison Operator

In [165]:
a1

array([1, 2, 3])

In [164]:
a2

array([[1, 2, 3],
       [4, 6, 7],
       [5, 8, 9]])

In [160]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [161]:
a1 > a2 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Sorting Array

In [167]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [168]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [169]:
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]], dtype=int64)

In [170]:
a1

array([1, 2, 3])

In [171]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [174]:
np.argmin(random_array,axis=1)

array([1, 1, 0], dtype=int64)

In [175]:
np.argmax(random_array,axis=1)

array([0, 3, 2], dtype=int64)

# Practical Example on Numpy (Images to Array)

<img src="numpy-images/panda.png">

In [179]:
from matplotlib.image  import imread

In [180]:
panda = imread('numpy-images/panda.png')
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [181]:
type(panda)

numpy.ndarray

In [182]:
panda.size, panda.shape , panda.ndim

(24465000, (2330, 3500, 3), 3)